# Generated by Django 3.2.9 on 2021-11-30 15:03

from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, primary_key=True, serialize=False, unique=True, verbose_name='CPF ')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Formato DDD + Número', max_length=128, region=None)),
                ('email', models.EmailField(max_length=255)),
                ('creation', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_cpf', localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF de origem')),
                ('target_cpf', localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF de destino')),
                ('value', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('number', models.UUIDField(default=uuid.uuid4)),
                ('balance', models.PositiveIntegerField(blank=True, default=5000)),
                ('account_user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account_user_id', serialize=False, to='DjangoLivre.client')),
            ],
        ),
    ]
