# Generated by Django 3.2.9 on 2021-12-01 18:52

from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', localflavor.br.models.BRCPFField(help_text='Formato: 00011122233', max_length=14, primary_key=True, serialize=False, verbose_name='CPF ')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Formato DDD + Número', max_length=128, region='BR', verbose_name='Telefone')),
                ('email', models.EmailField(max_length=255)),
                ('creation', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_cpf', localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF do usuário de origem')),
                ('target_cpf', localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF do usuário de destino')),
                ('value', models.FloatField(default=0, verbose_name='Valor')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('number', models.UUIDField(default=uuid.uuid4, verbose_name='Número da Conta')),
                ('balance', models.PositiveIntegerField(blank=True, default=5000, verbose_name='Saldo')),
                ('account_user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account_user_id', serialize=False, to='DjangoLivre.client', verbose_name='Cliente')),
            ],
        ),
    ]
