# Generated by Django 3.2.9 on 2021-11-30 20:48

from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoLivre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account_user_id', serialize=False, to='DjangoLivre.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.PositiveIntegerField(blank=True, default=5000, verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Número da Conta'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Formato DDD + Número', max_length=128, region='BR', verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='source_cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF do usuário de origem'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='target_cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF do usuário de destino'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='value',
            field=models.FloatField(default=0, verbose_name='Valor'),
        ),
    ]
